// AAAAAAAAAAAA Lanches AAAAAAAAAAAAAA \\

POST http://localhost:3000/lanches
Content-Type: application/json

{
    "nome": "Coxinha de frango com catupiry" ,
    "preço": 11.00
}

###

DELETE http://localhost:3000/lanches/2
Content-Type: application/json

###

PUT http://localhost:3000/lanches/1
Content-Type: application/json

{
    "id": "1",
    "nome": "Pastel de Pizza Na Promo",
    "preço": 2.50
}

//AAAAAAAAAAA Borracha AAAAAAAAAAAAAA \\

###

POST http://localhost:3000/coisas-de-borracha
Content-Type: application/json

{
    "id": "4",
    "nome": "Coisa-De-Borracha",
    "preço": 12.99
}

###

DELETE http://localhost:3000/coisas-de-borracha/1
Content-Type: application/json